export {
  isGitHubUrl,
  parseGitHubUrl,
  isGitLabUrl,
  isVCSUrl,
  parseVCSUrl,
  buildCloneUrl,
  isGitRepository,
  isBareGitRepository,
  getCurrentBranch,
  getHeadSha,
  getHeadCommitInfo,
  getRefCommitInfo,
  type HeadCommitInfo,
  listBranches,
  listRemoteBranches,
  fetchRemote,
  fetchAndFastForward,
  getBranchInfo,
  getBranchStatus,
  checkoutBranch,
  deleteBranch,
  pullBranch,
  stashPullPop,
  resetLocalChanges,
  getRemoteUrl,
  getRepoStatus,
  getRepoChanges,
  getRepoFileDiff,
  getRepoCommitChanges,
  getRepoCommitDiff,
  getRepoDeliveryStatus,
  getRepoRefSha,
  parseGitStatusPorcelain,
  getCloneBaseDir,
  repoToDirName,
  dirNameToRepo,
  listClonedRepos,
  normalizeLocalRepoPath,
  validateRepoInput,
  validateBranchName,
  sanitizeBranchName,
  type ParsedVCSUrl,
  type RepoBranchInfo,
  type RepoStatus,
  type RepoChanges,
  type RepoFileDiff,
  type RepoCommitChange,
  type RepoCommitDiff,
  type RepoDeliveryStatus,
  type GitFileChange,
  type FileChangeStatus,
  type BranchStatus,
  type BranchValidationResult,
  type ClonedRepoInfo,
  type ValidationResult,
} from "./git-utils";

export {
  isGitAuthError,
  isSSHAuthError,
  isHTTPSAuthError,
  getGitAuthErrorType,
  getGitAuthErrorMessage,
  getGitCredentialSetupInstructions,
  getGitErrorMessage,
  withGitAuthHandling,
  type GitAuthErrorType,
  type GitCredentialInstructions,
  type GitOperationResult,
} from "./git-error-handler";

export {
  stageFiles,
  unstageFiles,
  discardChanges,
  createCommit,
  pullCommits,
  rebaseBranch,
  resetBranch,
  getCommitList,
  getFileDiff,
  getCommitDiff,
  type CommitInfo,
} from "./git-operations";
