/**
 * Canvas Artifact model — metadata and type definitions for canvas artifacts.
 *
 * A canvas artifact is a self-contained, persisted analytical view generated
 * by an agent. The agent produces **constrained TSX source code** that only
 * imports from the Canvas SDK whitelist.  The viewer compiles and executes
 * the source inside a sandboxed runtime.
 *
 * Two render paths are supported:
 *  1. **dynamic** — `source` contains TSX; compiled + executed client-side.
 *  2. **prebuilt** — `canvasType` selects a pre-built template; `data` fills it.
 */

/** Known pre-built canvas template identifiers. */
export type CanvasType = "fitness_overview";

/** Render mode discriminator. */
export type CanvasRenderMode = "dynamic" | "prebuilt";

/** Metadata stored alongside the canvas artifact to drive the viewer. */
export interface CanvasArtifactMetadata {
  /** How the canvas should be rendered. */
  renderMode: CanvasRenderMode;
  /** Pre-built template selector (required when renderMode = "prebuilt"). */
  canvasType?: CanvasType;
  /** Human-readable title for the artifact. */
  title: string;
  /** Schema version of the canvas payload format. */
  schemaVersion: number;
  /** ISO 8601 timestamp of when the content was generated. */
  generatedAt: string;
  /** Optional workspace/codebase/task scope identifiers. */
  workspaceId?: string;
  codebaseId?: string;
  repoPath?: string;
}

/**
 * Shape of a canvas artifact as persisted.
 *
 * The artifact's `content` field (from the base Artifact model) stores the
 * JSON-serialized payload.
 */
export interface CanvasArtifactPayload {
  metadata: CanvasArtifactMetadata;
  /**
   * TSX source code generated by the agent.
   * Present when `renderMode === "dynamic"`.
   * The source must `export default` a React function component.
   * Only imports from `routa/canvas` are recommended. Legacy
   * `cursor/canvas` and `@canvas-sdk` aliases remain available for
   * previously generated artifacts.
   */
  source?: string;
  /**
   * Structured JSON data consumed by a pre-built canvas template.
   * Present when `renderMode === "prebuilt"`.
   */
  data?: unknown;
}

/**
 * Create a canvas artifact metadata record from common parameters.
 */
export function createCanvasMetadata(
  params: Omit<CanvasArtifactMetadata, "schemaVersion" | "renderMode"> & {
    schemaVersion?: number;
    renderMode?: CanvasRenderMode;
  },
): CanvasArtifactMetadata {
  return {
    schemaVersion: params.schemaVersion ?? 1,
    renderMode: params.renderMode ?? "dynamic",
    ...params,
  };
}
