/**
 * Workspace model
 *
 * Top-level organizational unit in Routa. Every agent, task, note,
 * session, and codebase belongs to exactly one workspace.
 */

import os from "os";
import path from "path";

export type WorkspaceStatus = "active" | "archived";

export interface Workspace {
  id: string;
  title: string;
  status: WorkspaceStatus;
  metadata: Record<string, string>;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Check whether a worktreeRoot value was auto-generated (not user-configured).
 * Auto-generated paths follow the pattern ~/.routa/workspace/{id} or
 * {ROUTA_WORKTREE_ROOT}/{id}. User-configured values are anything else.
 */
function isAutoGeneratedWorktreeRoot(worktreeRoot: string, workspaceId: string): boolean {
  const defaultRoot = path.join(os.homedir(), ".routa", "workspace", workspaceId);
  if (worktreeRoot === defaultRoot) return true;

  const envRoot = process.env.ROUTA_WORKTREE_ROOT?.trim();
  if (envRoot && worktreeRoot === path.join(envRoot, workspaceId)) return true;

  return false;
}

export function getDefaultWorkspaceWorktreeRoot(workspaceId: string): string {
  const envRoot = process.env.ROUTA_WORKTREE_ROOT?.trim();
  if (envRoot) return path.join(envRoot, workspaceId);
  return path.join(os.homedir(), ".routa", "workspace", workspaceId);
}

export function getEffectiveWorkspaceMetadata(workspace: Pick<Workspace, "id" | "metadata">): Record<string, string> {
  const metadata = { ...(workspace.metadata ?? {}) };
  const explicitRoot = metadata.worktreeRoot?.trim();
  // Let ROUTA_WORKTREE_ROOT override auto-generated defaults, but preserve
  // truly user-configured paths (e.g. set via workspace settings API).
  if (explicitRoot && !isAutoGeneratedWorktreeRoot(explicitRoot, workspace.id)) {
    metadata.worktreeRoot = explicitRoot;
  } else {
    metadata.worktreeRoot = getDefaultWorkspaceWorktreeRoot(workspace.id);
  }
  return metadata;
}

export function createWorkspace(params: {
  id: string;
  title: string;
  metadata?: Record<string, string>;
}): Workspace {
  const now = new Date();
  return {
    id: params.id,
    title: params.title,
    status: "active",
    metadata: getEffectiveWorkspaceMetadata({
      id: params.id,
      metadata: params.metadata ?? {},
    }),
    createdAt: now,
    updatedAt: now,
  };
}
